export const CREATE_ORDER = 'order/CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'order/CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'order/CREATE_ORDER_ERROR';

export const UPDATE_ORDER = 'order/UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'order/UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_ERROR = 'order/UPDATE_ORDER_ERROR';

export const REFUND_ORDER = 'order/REFUND_ORDER';
export const REFUND_ORDER_SUCCESS = 'order/REFUND_ORDER_SUCCESS';
export const REFUND_ORDER_ERROR = 'order/REFUND_ORDER_ERROR';
