export const FETCH_PRODUCT_SUCCESS = 'product/FETCH_PRODUCT_SUCCESS';

export const FETCH_WISHLIST = 'product/FETCH_WISHLIST';
export const FETCH_WISHLIST_SUCCESS = 'product/FETCH_WISHLIST_SUCCESS';
export const FETCH_WISHLIST_ERROR = 'product/FETCH_WISHLIST_ERROR';

export const GET_PRODUCT_ATTRIBUTE = 'product/GET_PRODUCT_ATTRIBUTE';
export const GET_PRODUCT_ATTRIBUTE_SUCCESS = 'product/GET_PRODUCT_ATTRIBUTE_SUCCESS';
export const GET_PRODUCT_ATTRIBUTE_ERROR = 'product/GET_PRODUCT_ATTRIBUTE_ERROR';

export const SORT_BY_PRODUCT = 'product/SORT_BY_PRODUCT';

export const FILTER_BY_PRODUCT = 'product/FILTER_BY_PRODUCT';
export const CLEAR_FILTER = 'product/CLEAR_FILTER';

export const ADD_RECENT_KEYWORD = 'product/ADD_RECENT_KEYWORD';
export const REMOVE_RECENT_KEYWORD = 'product/REMOVE_RECENT_KEYWORD';

export const FETCH_REVIEW = 'product/FETCH_REVIEW';
export const FETCH_REVIEW_SUCCESS = 'product/FETCH_REVIEW_SUCCESS';
export const FETCH_REVIEW_ERORR = 'product/FETCH_REVIEW_ERORR';

export const ADD_REVIEW = 'product/ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'product/ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_ERROR = 'product/ADD_REVIEW_ERROR';

export const FETCH_RATING = 'product/FETCH_RATING';
export const FETCH_RATING_SUCCESS = 'product/FETCH_RATING_SUCCESS';
export const FETCH_RATING_ERROR = 'product/FETCH_RATING_ERROR';
